apiVersion: v1
kind: Service
metadata:
  labels:
    app: istiod
    app.kubernetes.io/instance: istio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.27.1
    helm.sh/chart: istiod-1.27.1
    install.operator.istio.io/owning-resource: unknown
    istio: pilot
    istio.io/rev: llm-d-gateway
    operator.istio.io/component: Pilot
    release: istio
  name: istiod-llm-d-gateway
  namespace: llm-d-istio-system
spec:
  ports:
  - name: grpc-xds
    port: 15010
    protocol: TCP
  - name: https-dns
    port: 15012
    protocol: TCP
  - name: https-webhook
    port: 443
    protocol: TCP
    targetPort: 15017
  - name: http-monitoring
    port: 15014
    protocol: TCP
  selector:
    app: istiod
    istio.io/rev: llm-d-gateway

