# ------------------------------------------------------------------------------
# VLLM Simulator
#
# This deploys a VLLM simulator which can be used to simulate inference for
# small environments (e.g. Kubernetes In Docker (KIND) clusters), or for when
# all that is needed is some basic functionality.
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployments.yaml

images:
- name: quay.io/llm-d/vllm-sim
  newTag: 0.0.2
