apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: ${POOL_NAME}
spec:
  targetPortNumber: 8000
  selector:
    app: ${POOL_NAME}
  extensionRef:
    name: endpoint-picker
